#!/bin/sh
#
# @name Gazebo x500 Hexa
#
# @type Hexarotor
#

. ${R}etc/init.d/rc.mc_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=x500}

param set-default SIM_GZ_EN 1
param set-default CA_AIRFRAME 2
param set-default CA_ROTOR_COUNT 6

# --- Motor 0: Back Left ---
param set-default CA_ROTOR0_PX -0.209
param set-default CA_ROTOR0_PY -0.122
param set-default CA_ROTOR0_KM 0.05

# --- Motor 1: Front Right ---
param set-default CA_ROTOR1_PX 0.211
param set-default CA_ROTOR1_PY 0.119
param set-default CA_ROTOR1_KM -0.05

# --- Motor 2: Back Right ---
param set-default CA_ROTOR2_PX -0.209
param set-default CA_ROTOR2_PY 0.122
param set-default CA_ROTOR2_KM -0.05

# --- Motor 3: Front Left ---
param set-default CA_ROTOR3_PX 0.211
param set-default CA_ROTOR3_PY -0.119
param set-default CA_ROTOR3_KM 0.05

# --- Motor 4: Middle Left ---
param set-default CA_ROTOR4_PX 0.0
param set-default CA_ROTOR4_PY -0.242
param set-default CA_ROTOR4_KM -0.05

# --- Motor 5: Middle Right ---
param set-default CA_ROTOR5_PX 0.0
param set-default CA_ROTOR5_PY 0.242
param set-default CA_ROTOR5_KM 0.05

# --- ربط القنوات وتصحيح الـ MIN/MAX لـ 6 مواتير ---
param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_FUNC4 104
param set-default SIM_GZ_EC_FUNC5 105
param set-default SIM_GZ_EC_FUNC6 106

param set-default SIM_GZ_EC_MIN1 150
param set-default SIM_GZ_EC_MIN2 150
param set-default SIM_GZ_EC_MIN3 150
param set-default SIM_GZ_EC_MIN4 150
param set-default SIM_GZ_EC_MIN5 150
param set-default SIM_GZ_EC_MIN6 150

param set-default SIM_GZ_EC_MAX1 1000
param set-default SIM_GZ_EC_MAX2 1000
param set-default SIM_GZ_EC_MAX3 1000
param set-default SIM_GZ_EC_MAX4 1000
param set-default SIM_GZ_EC_MAX5 1000
param set-default SIM_GZ_EC_MAX6 1000

param set-default PWM_MAIN_FUNC7 2048
param set-default PWM_MAIN_FUNC8 2049
param set-default PWM_MAIN_FUNC9 2050

param set-default MNT_MODE_IN 3
param set-default MNT_MODE_OUT 2

param set-default MPC_THR_HOVER 0.50
param set-default NAV_DLL_ACT 2



